Added common abbreviations
SW705E19/report pull request #18
Opened 2019-10-09 08:49 UTC by Moesgaarda

2019-10-09 08:49 UTC, Moesgaarda commented
![](https://github.trello.services/images/mini-trello-icon.png) [Skriv ned i terms hvad "service" er (det en tutor tilbyder)](https://trello.com/c/2725oP5h/42-skriv-ned-i-terms-hvad-service-er-det-en-tutor-tilbyder)

2019-10-14 08:22 UTC, Eduardsen requested changes

2019-10-14 08:22 UTC, Eduardsen commented on sections/abbreviations.tex
> +    \textbf{User} &: \text{A person who uses the system} \\
```suggestion
    \textbf{User} &: \text{A person who uses the system. Can be both a tutor or a student.} \\
```

2019-10-14 08:39 UTC, andpaacoke approved these changes

2019-10-14 08:42 UTC, Eduardsen approved these changes

2019-10-14 08:51 UTC, merged