latex setup
SW705E19/report pull request #2
Opened 2019-09-11 11:19 UTC by MathiasLybech

fuck mit liv

2019-09-11 11:27 UTC, Tekrus requested changes

2019-09-11 11:27 UTC, Moesgaarda commented on .vscode/settings.json
> +{
tror ikke at den her fil skal med

2019-09-11 11:27 UTC, Moesgaarda commented on .vscode/spellright.dict
> +Weekplanner
tror ikke at den her fil skal med

2019-09-11 11:27 UTC, Moesgaarda commented on bib/mybib.bib
> +@BOOK{Sebesta,
måske rydde bib filen, tror ikke vi skal bruge de her kilder igen

2019-09-11 11:27 UTC, Moesgaarda commented on master.tex
> +%\listoftodos
??????? vi har trello nu

2019-09-11 11:27 UTC, Moesgaarda commented on sections/abbreviations.tex
> +    \textbf{PO} &: \text{Product Owner} \\
```suggestion
    \textbf{Term} &: \text{Description} \\
```

2019-09-11 11:27 UTC, Moesgaarda commented on sections/colophon.tex
> +\noindent Copyright \copyright{} Aalborg University 2018\par
```suggestion
\noindent Copyright \copyright{} Aalborg University 2019\par
```

2019-09-11 11:27 UTC, Moesgaarda commented on sections/frontpage.tex
> +      Group: SW610f19%Insert your group name or real names here
```suggestion
      Group: SW705E19%Insert your group name or real names here
```

2019-09-11 11:27 UTC, Moesgaarda commented on sections/titlepages.tex
> +     Bache %theme
generel opdatering af den her side

2019-09-11 11:31 UTC, Moesgaarda commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sæt LaTeX skabelon op](https://trello.com/c/jCLbsoZI/2-s%C3%A6t-latex-skabelon-op)

2019-09-11 19:36 UTC, Tekrus approved these changes

2019-09-12 09:09 UTC, andpaacoke approved these changes
Flot mathias :)

2019-09-12 09:10 UTC, merged