er description
SW705E19/report pull request #27
Opened 2019-10-22 14:18 UTC by Eduardsen

2019-10-22 15:45 UTC, Tekrus requested changes

2019-10-22 15:45 UTC, Moesgaarda commented on sections/design/erd-diagram.tex
> +This is a way to gain a better understanding of the requirements of the database and to ensure its design is clear.
```suggestion
It serves as a way to gain a better understanding of the requirements of the database and to ensure its design is clear.
```

2019-10-22 15:45 UTC, Moesgaarda commented on sections/design/erd-diagram.tex
> +An entity is a thing or an object in the real world that is distinguishable from other objects, and are described through a set of attributes.
```suggestion
An entity is usually an object in the real world that is distinguishable from other objects, and is described through a set of attributes.
```

2019-10-22 15:45 UTC, Moesgaarda commented on sections/design/erd-diagram.tex
> +Cardinalities are important for these relationships - they express the number of entities to which another entity can be associated\cite{DBConcepts}, either one or many.
```suggestion
Cardinalities are important for these relationships, as they express the number of entities to which another entity can be associated\cite{DBConcepts}, either one or many.
```

2019-10-22 15:45 UTC, Moesgaarda commented on sections/design/erd-diagram.tex
> +A message is associated with a sender, and at least one receiver.
```suggestion
Another example of a many-to-many relation is users and messages, where a message is associated with a sender, and at least one receiver.
```

2019-10-22 15:45 UTC, Moesgaarda commented on sections/design/erd-diagram.tex
> +This is what the arrow from both \textit{tutor} and \textit{admin} represent.
```suggestion
This is achieved in the ER diagram by modeling them as subtypes, defining an \textit{ISA} relationship, which is represented by the arrow from both \textit{tutor} and \textit{admin}.
```

2019-10-22 21:42 UTC, andpaacoke approved these changes

2019-10-23 07:20 UTC, Tekrus approved these changes

2019-10-23 07:23 UTC, merged