[WIP]Recommender stuff
SW705E19/report pull request #47
Opened 2019-12-12 09:09 UTC by Eduardsen

2019-12-12 13:27 UTC, MathiasLybech requested changes

2019-12-12 13:27 UTC, MathiasLybech commented on sections/implementation/recommender.tex
>  \subsection{Pros and cons}
Overvej evt at have en itemize eller lignende, således at content-based filtering og collaborative filtering bliver opstillet imod hinanden. Synes ellers det kan være svært at få et overblik.

2019-12-12 13:27 UTC, MathiasLybech commented on sections/implementation/recommender.tex
> +For example, for a movies, the factors could be thought of as measuring obvious dimensions such as amount of action, less well-defined dimensions such as character development or uninterpretable dime
```suggestion
For example, for movies, the factors could be thought of as measuring obvious dimensions such as amount of action, less well-defined dimensions such as character development or uninterpretable dimensions \cite{MatrixFactorization}.
```

2019-12-12 13:27 UTC, MathiasLybech commented on sections/implementation/recommender.tex
> + In \autoref{fig:minimizesquatederror}, $K$ is the set of $(u, i)$ pairs for which the rating $r_{ui}$ is known.
Noget fucker her. Man kan ikke se autoref

2019-12-12 13:27 UTC, MathiasLybech commented on sections/implementation/recommender.tex
> +\subsection{Collaborative filtering through a latent factor model}
Det her afsnit har jeg svært ved at forstå :derpesseddoggo:

2019-12-12 13:27 UTC, MathiasLybech commented on sections/implementation/recommender.tex
> +     \caption{A simplified illustration of a latent factor approach.}
opdater captions

2019-12-12 13:27 UTC, MathiasLybech commented on sections/implementation/recommender.tex
> + This regularization is the second term of the equation, where $\lambda$ is an arbitrary constant that controls the extent of the regularization.
Fortæl explicit hvad the second term er

2019-12-13 09:22 UTC, jenspetur94 approved these changes

2019-12-13 09:47 UTC, MathiasLybech commented on sections/implementation/recommender.tex
>  \subsection{Pros and cons}
```suggestion
\subsection{Pros and cons}\label{sec:recommender-pros-and-cons}
```

2019-12-13 11:02 UTC, MathiasLybech approved these changes

2019-12-13 11:03 UTC, merged