Prob analysis summary
SW705E19/report pull request #56
Opened 2019-12-13 13:31 UTC by Eduardsen

summary i guess?

2019-12-14 08:50 UTC, Tekrus requested changes

2019-12-14 08:50 UTC, Moesgaarda commented on sections/problem-analysis/summary.tex
> +Finally we defined our process, basing it around short, weekly sprints.
Kunne godt tænke mig at der stod mere med hvad det faktisk indeholder, sådan at man nærmest bare kan læse summary og have den viden der er i rapporten.

fx. We determined that scalability can be split into the x categories a, b, c and d........ and found some important principles such as......

2019-12-15 11:05 UTC, Tekrus requested changes

2019-12-15 11:05 UTC, Moesgaarda commented on sections/problem-analysis/summary.tex
> +    \item MAke maintenance and automation easy
```suggestion
    \item Make maintenance and automation easy
```

2019-12-15 11:22 UTC, Tekrus approved these changes

2019-12-15 13:23 UTC, MathiasLybech approved these changes

2019-12-15 13:23 UTC, merged