added intros
SW705E19/report pull request #58
Opened 2019-12-15 15:35 UTC by Eduardsen

2019-12-15 16:24 UTC, Tekrus requested changes

2019-12-15 16:24 UTC, Moesgaarda commented on sections/implementation/implementation.tex
> +Finally, we will discuss recommender systems, which choice of recommendation approach we chose, and how we implemented it.
```suggestion
Finally, we will discuss recommender systems, which choice of recommendation approach we chose, and how it was implemented.
```

2019-12-15 16:24 UTC, Moesgaarda commented on sections/problem-analysis/problem-analysis.tex
> +Finally, we will quickly explain the process with which the system will be created.
wat

2019-12-15 16:24 UTC, Moesgaarda commented on sections/problem-definition/problem-definition.tex
> +In this chapter we will examine the requirements of the system, construct a MoSCoW analysis of the requirements defining a minimum viable product, and finally update the problem statement to reflect
```suggestion
In this chapter we will examine the requirements of the system, construct a MoSCoW analysis of the requirements defining a minimum viable product, and finally update the problem statement to reflect what we deemed to be the minimum viable product.
```

2019-12-15 16:25 UTC, Eduardsen commented on sections/problem-analysis/problem-analysis.tex
> +Finally, we will quickly explain the process with which the system will be created.
wat hvad

2019-12-15 16:27 UTC, Moesgaarda commented on sections/problem-analysis/problem-analysis.tex
> +Finally, we will quickly explain the process with which the system will be created.
```suggestion
Finally, we will give a brief outcast of the work together process we used.
```

2019-12-15 16:28 UTC, Eduardsen commented on sections/problem-analysis/problem-analysis.tex
> +Finally, we will quickly explain the process with which the system will be created.
man bliver så træt

2019-12-15 16:29 UTC, Moesgaarda commented on sections/problem-analysis/problem-analysis.tex
> +Finally, we will quickly explain the process with which the system will be created.
```suggestion
Finally, we will give a brief overview of the collaborative process under which the system was created.
```

2019-12-16 07:25 UTC, Tekrus approved these changes

2019-12-16 07:33 UTC, andpaacoke approved these changes

2019-12-16 07:46 UTC, merged