Initial abstract
SW705E19/report pull request #63
Opened 2019-12-16 10:24 UTC by Moesgaarda

2019-12-16 13:27 UTC, jenspetur94 requested changes

2019-12-16 13:27 UTC, jenspetur94 commented on sections/titlepages.tex
> +It includes creating a set of personas for helping the design process, using the MoSCoW analysis model to define a minimum viable product and finally how the service is implemented using React for th
virker lidt underligt at du skriver finally to gange i streg

2019-12-16 13:34 UTC, jenspetur94 approved these changes

2019-12-17 09:19 UTC, Fatdet approved these changes

2019-12-17 09:22 UTC, merged