design summary
SW705E19/report pull request #64
Opened 2019-12-16 10:24 UTC by Eduardsen

2019-12-16 14:28 UTC, MathiasLybech approved these changes

2019-12-16 14:40 UTC, Tekrus requested changes

2019-12-16 14:40 UTC, Moesgaarda commented on sections/design/design-summary.tex
> +To give the developer's a sense of the visual design, we created prototypes for the different parts of the system.
```suggestion
To give the developers a sense of the visual design, we created prototypes for the different parts of the system.
```

2019-12-16 14:40 UTC, Moesgaarda commented on sections/design/design-summary.tex
> +We chose to use a relational database since ACID compliance is an important part of the system.
slå det om ACID sammen til en

2019-12-16 14:40 UTC, Moesgaarda commented on sections/design/design-summary.tex
> +We chose to use Postgres because of experience.
```suggestion
```

2019-12-17 09:05 UTC, Tekrus requested changes

2019-12-17 09:05 UTC, Moesgaarda commented on sections/design/design-summary.tex
> +We researched React, a JavaScript library, and determined it is a popular choice for frontend development with an extensive ecosystem.
```suggestion
We researched React, a JavaScript library, and determined it is a popular choice for front end development with an extensive ecosystem.
```

2019-12-17 09:05 UTC, Moesgaarda commented on sections/design/design-summary.tex
> +When atomicity, consistency, isolation and durability are important a relational database should be considered.
```suggestion
When atomicity, consistency, isolation and durability (ACID) are important a relational database should be considered.
```

2019-12-17 09:05 UTC, Moesgaarda commented on sections/design/design-summary.tex
> +Finally, we defined an ERD-diagram to give a sense of the structure of the database.
```suggestion
Finally, we defined an ER diagram to give a sense of the structure of the database.
```

2019-12-17 09:05 UTC, MathiasLybech approved these changes

2019-12-17 09:38 UTC, Tekrus approved these changes

2019-12-17 09:38 UTC, merged