usability ting
SW705E19/report pull request #66
Opened 2019-12-16 14:06 UTC by Eduardsen

2019-12-16 14:26 UTC, MathiasLybech requested changes

2019-12-16 14:26 UTC, MathiasLybech commented on sections/appendix/usability-test.tex
> +    \item Create a new category
```suggestion
```

2019-12-16 14:26 UTC, MathiasLybech commented on sections/appendix/usability-test.tex
> +The administrator part:
```suggestion
The tutor part:
```

2019-12-16 14:26 UTC, MathiasLybech commented on sections/testing/usability-testing.tex
> +The password requires at least 8 characters, with one number and one capital character.
Dette er ikke helt rigtigt. De skrev forkert password, som blev prompted, men derefter oprettede den det alligevel. Valideringen på password virker derfor ikke.

2019-12-16 14:26 UTC, MathiasLybech commented on sections/testing/usability-testing.tex
> +\\\\
Du må gerne tilføje et lille afsnit omkring buggen med, at hvis man er på en anden bruger, så kan man ikke komme direkte over til sin egen bruger ved at trykker på account iconet. 
Samtlige deltagere gjorde dette, men eftersom at det ikke sendte dem videre, så blev jeg nødt til at bede dem om at gå ind på landing pagen først.

2019-12-16 14:43 UTC, Eduardsen commented on sections/testing/usability-testing.tex
> +\\\\
jeg ved ikke om jeg følger med forklaringen her 🤔

2019-12-17 08:55 UTC, jenspetur94 requested changes

2019-12-17 08:55 UTC, jenspetur94 commented on sections/appendix/usability-test.tex
> +    \item Choose an arbitrary service and determined the accepted payments for the given tutor
tror ikke at der er nogen der lavede den her fordi at den ikke rigtig gav mening

2019-12-17 08:55 UTC, jenspetur94 commented on sections/appendix/usability-test.tex
> +    \item Create a new category
der var ingen der lavede den her

2019-12-17 08:55 UTC, jenspetur94 commented on sections/appendix/usability-test.tex
> +    \item Change language from English to Danish
log ind mangler vist her

2019-12-17 11:36 UTC, jenspetur94 requested changes

2019-12-17 11:36 UTC, jenspetur94 commented on sections/testing/usability-testing.tex
> +Multiple testers inputted a password that did not live up to the restrictions, but the users were still created.
```suggestion
Multiple testers input a password that did not live up to the restrictions, but the users were still created. 
```

2019-12-17 11:36 UTC, jenspetur94 commented on sections/testing/usability-testing.tex
> +The system then assumes that the state doe snot need to be updated, as the content of the page should be the same.
```suggestion
The system then assumes that the state doe not need to be updated, as the content of the page should be the same.
```

2019-12-17 12:29 UTC, MathiasLybech approved these changes

2019-12-17 12:42 UTC, jenspetur94 approved these changes

2019-12-17 12:42 UTC, merged