i18n updates
SW705E19/report pull request #68
Opened 2019-12-16 14:38 UTC by Eduardsen

2019-12-16 14:44 UTC, Tekrus requested changes

2019-12-16 14:44 UTC, Moesgaarda commented on sections/implementation/i18n.tex
> +Being an internationalization framework means it allows software to be adapted to several languages.
skriv noget om forskel på internationalization og localization

2019-12-17 09:23 UTC, Tekrus approved these changes

2019-12-17 11:37 UTC, jenspetur94 approved these changes

2019-12-17 11:37 UTC, merged